# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Timeout for starship to scan files (in milliseconds).
scan_timeout = 30

# Timeout for commands executed by starship (in milliseconds).
command_timeout = 5000

# Inserts a blank line between shell prompts
add_newline = false

[username]
style_user = "blue bold"
style_root = "black bold"
format = '\[[$user]($style)'
show_always = true

[hostname]
ssh_only = false
format = '@[$hostname]($style)\] '
style = "bold green"

[directory]
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold cyan"
read_only = " "

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = "⌘ "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = " "

[meson]
symbol = "喝 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[spack]
symbol = "🅢 "
