#!/usr/bin/env bash

## Get colors from .Xresources --------------------------------#
xrdb -I"$HOME" ~/.Xresources
function get_colors() {
  BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
  GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
  BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
  MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
}
get_colors

## Configurations ---------------------------------------------#
pgrep -x sxhkd > /dev/null || sxhkd &

# Check local machine
HOSTNAME=$(hostnamectl hostname)
if [[ "$HOSTNAME" == "canaima" ]]; then
  monitors # Configure monitor

  # Add workspaces to primary monitor
  bspc monitor LVDS1 -d I II III IV V

  # Check if monitor is connected
  CONNECTED=$(xrandr -q | grep -w 'connected' | grep -w 'VGA1' | awk '{print $2}')
  if [[ "$CONNECTED" == "connected" ]]; then
    # Add workspaces to monitor
    bspc monitor VGA1 -d VI VII VIII IX
  else
    # Remove second monitor
    bspc monitor VGA1 -r
  fi
fi

# Global settings
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config focused_border_color "$BLUE" 
bspc config presel_feedback_color "$GREEN"
bspc config split_ratio 0.50
bspc config presel_feedback true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config center_pseudo_tiled true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config window_gap 3
bspc config border_width 1

## Window rules -----------------------------------------------#

# Remove all rules first
bspc rule -r "*:*"

## Autostart --------------------------------------------------#

# Set wallpaper
"$HOME"/.fehbg

# Set colors
bspcolors

# Network interface
"$HOME"/.local/bin/network-interface

# Launch polybar
"$HOME"/.config/polybar/launch.sh
