#!/usr/bin/env bash

######################################################################
#  ____ ____  ______        ____  __    ____             __ _
# | __ ) ___||  _ \ \      / /  \/  |  / ___|___  _ __  / _(_) __ _
# |  _ \___ \| |_) \ \ /\ / /| |\/| | | |   / _ \| '_ \| |_| |/ _` |
# | |_) |__) |  __/ \ V  V / | |  | | | |__| (_) | | | |  _| | (_| |
# |____/____/|_|     \_/\_/  |_|  |_|  \____\___/|_| |_|_| |_|\__, |
#                                                             |___/
######################################################################

## Bspwm config directory
BSPWM_DIR="${HOME}/.config/bspwm"

## Export bspwm/bin dir to PATH
export PATH="${PATH}:$BSPWM_DIR/scripts"
export XDG_CURRENT_DESKTOP="bspwm"

## Get colors from .Xresources --------------------------------#
xrdb -I"${HOME}" ~/.Xresources
BACKGROUND=$(xgetres 'background')
GREEN=$(xgetres 'color2')
BLUE=$(xgetres 'color4')
MAGENTA=$(xgetres 'color5')

## Configurations ---------------------------------------------#

## Manage Monitors and Workspaces

# Check local machine
HOSTNAME=$(hostnamectl hostname)
if [[ "${HOSTNAME}" == "canaima" ]]; then
  # Add workspaces to primary monitor
  bspc monitor LVDS1 -d '1' '2' '3' '4' '5'

  # Check if monitor is connected
  CONNECTED=$(xrandr -q | grep -w 'connected' | grep -w 'VGA1' | awk '{print $2}')
  if [[ "${CONNECTED}" == "connected" ]]; then
    # Add workspaces to monitor
    bspc monitor VGA1 -d '6' '7' '8' '9'
    # Configure monitors
    configure-monitors
  else
    # Remove second monitor
    bspc monitor VGA1 -r
    # Configure monitors
    configure-monitors
  fi
fi

# Global settings
bspc config normal_border_color "${BACKGROUND}"
bspc config active_border_color "${MAGENTA}"
bspc config focused_border_color "${BLUE}"
bspc config presel_feedback_color "${GREEN}"
bspc config split_ratio 0.50
bspc config presel_feedback true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config center_pseudo_tiled true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config window_gap 4
bspc config border_width 0

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

## Window rules -----------------------------------------------#

# Remove all rules first
bspc rule -r "*:*"

## Autostart --------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd bspc

# Start xsettingsd daemon
xsettingsd --config="${BSPWM_DIR}/xsettingsd" &

# Start hotkeys daemon
pgrep -x sxhkd >/dev/null || sxhkd &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore walpaper
bash ~/.fehbg

# Start bspwm scripts
bash bspwm_colors
bash bspwm_screenshot
bash bspwm_compositor
bash bspwm_statusbar
