#!/bin/bash

## Bspwm config directory
BSPDIR="${HOME}/.config/bspwm"

## Export Bspwm scripts to PATH
export PATH="${PATH}:${BSPDIR}/scripts"

## Get colors from .Xresources --------------------------------#
xrdb -I"${HOME}" ~/.Xresources
BACKGROUND=$(xgetres 'background')
GREEN=$(xgetres 'color2')
BLUE=$(xgetres 'color4')
MAGENTA=$(xgetres 'color5')

## Configurations ---------------------------------------------#

# Check local machine
HOSTNAME=$(hostnamectl hostname)
if [[ "${HOSTNAME}" == "canaima" ]]; then
  # Add workspaces to primary monitor
  bspc monitor LVDS1 -d '1' '2' '3' '4' '5'

  # Check if monitor is connected
  CONNECTED=$(xrandr -q | grep -w 'connected' | grep -w 'VGA1' | awk '{print $2}')
  if [[ "${CONNECTED}" == "connected" ]]; then
    # Add workspaces to monitor
    bspc monitor VGA1 -d '6' '7' '8' '9'
    # Configure monitors
    configure-monitors
  else
    # Remove second monitor
    bspc monitor VGA1 -r
    # Configure monitors
    configure-monitors
  fi
fi

# Global settings
bspc config normal_border_color "${BACKGROUND}"
bspc config active_border_color "${MAGENTA}"
bspc config focused_border_color "${BLUE}"
bspc config presel_feedback_color "${GREEN}"
bspc config split_ratio 0.50
bspc config presel_feedback true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config center_pseudo_tiled true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config window_gap 0
bspc config border_width 0

## Window rules -----------------------------------------------#

# Remove all rules first
bspc rule -r "*:*"

## Autostart --------------------------------------------------#

# Kill if already running
killall -9 sxhkd

# Reload xsettingsd daemon
killall -HUP xsettingsd

# Start hotkeys daemon
pgrep -x sxhkd >/dev/null || sxhkd &

# Restore walpaper
bash ~/.fehbg

# Start bspwm scripts
bash bsp-colors
bash bsp-statusbar
