#!/usr/bin/env bash

## Set colors from Xresources
## Rosmer Lopez <rosmerlopez99@gmail.com>

ROFI_FILE_COLORS="${HOME}/.config/bspwm/themes/rofi/shared/colors.rasi"

## Get colors from .Xresources
BACKGROUND=$(xgetres "background")
FOREGROUND=$(xgetres "foreground")
BLACK=$(xgetres "color0")
RED=$(xgetres "color1")
GREEN=$(xgetres "color2")
YELLOW=$(xgetres "color3")
BLUE=$(xgetres "color4")
MAGENTA=$(xgetres "color5")
CYAN=$(xgetres "color6")
WHITE=$(xgetres "color7")

## Set colors for rofi
function set_colors_rofi() {
  cat >"${ROFI_FILE_COLORS}" <<-_EOF_
* {
  background: ${BACKGROUND};
  foreground: ${FOREGROUND};
  color-black: ${BLACK};
  color-red: ${RED};
  color-green: ${GREEN};
  color-yellow: ${YELLOW};
  color-blue: ${BLUE};
  color-magenta: ${MAGENTA};
  color-cyan: ${CYAN};
  color-white: ${WHITE};
}
	_EOF_
}

set_colors_rofi
