#!/usr/bin/env bash

## Script to start compositor
## Rosmer Lopez <rosmerlopez99@gmail.com>

# Bspwm directory
BSPWM_DIR="${HOME}/.config/bspwm"

# Terminate if picom is already running
killall -q picom

# Wait until the processes have been shut down
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done

# Launch picom
picom --config "${BSPWM_DIR}/picom.conf" &
