#!/usr/bin/env bash

## Script to take screenshots
## Rosmer Lopez <rosmerlopez99@gmail.com>

# File
time=$(date +%Y-%m-%d-%H-%M-%S)
geometry=$(xrandr | grep "current" | head -n1 | cut -d"," -f2 | tr -d "[:blank:],current")
dir="$(xdg-user-dir PICTURES)/Screenshots"
file="Screenshot_${time}_${geometry}.png"

# Directory
if [[ ! -d "${dir}" ]]; then
  mkdir -p "${dir}"
fi

# Copy screenshot to clipboard
copy_shot() {
  tee "$file" | xclip -selection clipboard -t image/png
}

screenshot_now() {
  cd "${dir}" && maim -u -f png | copy_shot
}

screenshot_active_window() {
  cd "${dir}" && maim -u -f png -i "$(xdotool getactivewindow)" | copy_shot
}

screenshot_select_area() {
  cd "${dir}" && maim -u -f png -s -b 2 -c 0.35,0.55,0.85,0.25 -l | copy_shot
}

# Execute script
if [[ "${1}" == "--now" ]]; then
  screenshot_now
elif [[ "${1}" == "--win" ]]; then
  screenshot_active_window
elif [[ "${1}" == "--area" ]]; then
  screenshot_select_area
else
  echo -e "Available Options : --now --win --area"
fi

exit 0
