#!/usr/bin/env bash

## Rofi - Power Menu
## Rosmer Lopez <rosmerlopez99@gmail.com>

shutdown=""
reboot=""
lock=""
suspend="󰤄"
logout=""

prompt="$(whoami)@$(hostnamectl hostname) ($(echo -n "$DESKTOP_SESSION"))"
message="Uptime : $(uptime -p | sed "s/up //g")"
theme_rasi="${HOME}/.config/bspwm/themes/rofi/powermenu.rasi"

rofi_cmd() {
  rofi -dmenu -p "${prompt}" -mesg "${message}" -markup-rows -theme "${theme_rasi}"
}

run_rofi() {
  echo -e "${lock}\n${logout}\n${suspend}\n${reboot}\n${shutdown}" | rofi_cmd
}

# Actions
chosen="$(run_rofi)"
case "${chosen}" in
"${shutdown}")
  systemctl poweroff
  ;;
"${reboot}")
  systemctl reboot
  ;;
"${lock}")
  sleep 1
  dm-tool lock
  ;;
"${suspend}")
  sleep
  systemctl suspend
  ;;
"${logout}")
  bspc quit
  ;;
esac
